environment:
  nodejs_version: "18" # самая последняя стабильная версия

branches: # какие ветки отслеживаются
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование, чтобы node_modules работал быстрее

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования
