environment:
  nodejs_version: "18" # самая последняя стабильная версия

branches: # какие ветки отслеживаются
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование, чтобы node_modules работал быстрее

install:
  - npm install  # команда установки зависимостей
  - rm -rf node_modules/.cache  # Удалить кэш Webpack перед сборкой

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint  # скрипт тестирования
